import '@/styles/globals.css'
import Sidebar from "@/components/Sidebar";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className={'flex w-full'}>
          <div className={'bg-[#202020] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'}>
              <Sidebar/>
          </div>
          <div className={'bg-[#161616] flex-1'}>
              {children}
          </div>
      </div>
      </body>
    </html>
  )
}
