import '@/styles/globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {/*<Sidebar/>*/}
      {/*Notification*/}
      <div className={'bg-[#161616]'}>
        {children}
      </div>
      </body>
    </html>
  )
}
